name: chainlit
services:
  chainlit:
    container_name: chainlit
    depends_on:
      postgres:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=123456
      - BASE_URL=
      - API_KEY=
      - MODEL_NAME=DeepSeek-V3-0324
      - CHAINLIT_AUTH_SECRET=C
      - POSTGRES_DB=chainlit
      - POSTGRES_USER=chainlit
      - POSTGRES_PASSWORD=123456
      - THINK_BASE_URL=
      - THINK_API_KEY=
      - THINK_MODEL_NAME=DeepSeek-R1
      - USE_THINKING_MODEL=true
    image: fromxiaobai/custom-chainlit:v2
    ports:
      - '8000:8010'
    #volumes:
      #- ./resume.py:/app/app.py
      #- ./.env:/app/.env
    networks:
      - chainlit_network
  postgres:
    container_name: postgres
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
      - POSTGRES_DB=chainlit
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=chainlit
    image: fromxiaobai/pg:for-chainlit
    volumes:
      - /DATA/AppData/postgresql/data:/var/lib/postgresql/data
    networks:
      - chainlit_network
networks:
  chainlit_network:
    name: chainlit_network
    driver: bridge
x-casaos:
  architectures:
    - amd64
  author: CasaOS Team
  category: Chat
  description:
    en_us: >
      Chainlit is an open-source conversational AI application that delivers a
      seamless interactive experience, enabling users to communicate efficiently
      with AI through natural language. Designed for individuals and teams, it
      leverages powerful language models to help users handle tasks, gain
      insights, or engage in intelligent conversations.


      The application integrates with popular frameworks and large language model (LLM) providers, such as OpenAI, Mistral, LangGraph, LlamaIndex, and HuggingFace, ensuring users can flexibly connect to a wide range of AI tools and services. It supports data persistence, allowing users to collect, monitor, and analyze interaction data to enhance user experience and tailor it to specific needs.


      Chainlit offers multi-step reasoning visualization, enabling users to clearly understand the intermediate steps behind AI-generated outputs, improving transparency and control. With its intuitive user interface and multilingual support, it ensures accessibility for users worldwide. Whether for everyday tasks or complex conversations, Chainlit is the ideal choice for creating intelligent, user-friendly AI interactions.
    zh_cn: >
      Chainlit 是一款开源的对话式人工智能应用，提供无缝的交互体验，使用户能够通过自然语言与 AI
      高效沟通。它专为个人和团队设计，利用强大的语言模型帮助用户处理任务、获取见解或进行智能对话。


      该应用与流行框架和大型语言模型（LLM）提供商（如 OpenAI、Mistral、LangGraph、LlamaIndex 和 HuggingFace）集成，确保用户能够灵活连接各种 AI 工具和服务。它支持数据持久性，使用户可以收集、监控和分析交互数据，以优化用户体验并满足特定需求。


      Chainlit 提供多步骤推理可视化功能，让用户能够清晰了解 AI 生成输出的中间步骤，提升透明度和控制力。其直观的用户界面和多语言支持确保全球用户都能轻松使用。无论是日常任务还是复杂对话，Chainlit 都是创建智能、用户友好型 AI 交互的理想选择。
  developer: fromxiaobai
  icon: 
  main: chainlit
  port_map: "8010"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Dengwii/CasaOS-AppStore/blob/ai/Apps/Chainlit/icon.png
  store_app_id: chainlit
  tagline:
    en_us: Conversational AI application
    zh_cn: 对话式人工智能应用
  tips:
    before_install:
      en_us: |
        Default Account
        
        | Username | Password |
        |----------|----------|
        | `admin`    | `123456` |
      zh_cn: |
        默认账号
        
        | Username | Password   |
        | -------- | ---------- |
        | `admin`    | `123456` |
  title:
    custom: Chat
    en_us: Chat
    zh_cn: Chat
